/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/base/badge/index.vue')['default']
    BlockIcon: typeof import('./src/components/workflow/block-icon.vue')['default']
    Blocks: typeof import('./src/components/workflow/block-selector/blocks.vue')['default']
    BlockSelector: typeof import('./src/components/workflow/block-selector/index.vue')['default']
    Chat: typeof import('./src/components/strategy-detail/chat/index.vue')['default']
    ConditionAdd: typeof import('./src/components/workflow/nodes/if-else/components/condition-add.vue')['default']
    ConditionFilesListValue: typeof import('./src/components/workflow/nodes/if-else/components/condition-files-list-value.vue')['default']
    ConditionInput: typeof import('./src/components/workflow/nodes/if-else/components/condition-list/condition-input.vue')['default']
    ConditionItem: typeof import('./src/components/workflow/nodes/if-else/components/condition-list/condition-item.vue')['default']
    ConditionList: typeof import('./src/components/workflow/nodes/if-else/components/condition-list/index.vue')['default']
    ConditionNumberInput: typeof import('./src/components/workflow/nodes/if-else/components/condition-number-input.vue')['default']
    ConditionOperator: typeof import('./src/components/workflow/nodes/if-else/components/condition-list/condition-operator.vue')['default']
    ConditionValue: typeof import('./src/components/workflow/nodes/if-else/components/condition-value.vue')['default']
    ConditionVarSelector: typeof import('./src/components/workflow/nodes/if-else/components/condition-list/condition-var-selector.vue')['default']
    ConditionWrap: typeof import('./src/components/workflow/nodes/if-else/components/condition-wrap.vue')['default']
    Edge: typeof import('./src/components/workflow/edge/index.vue')['default']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    End: typeof import('./src/components/workflow/nodes/end/index.vue')['default']
    Header: typeof import('./src/components/Layout/Header/index.vue')['default']
    IfElse: typeof import('./src/components/workflow/nodes/if-else/index.vue')['default']
    Input: typeof import('./src/components/base/input/index.vue')['default']
    Llm: typeof import('./src/components/workflow/nodes/llm/index.vue')['default']
    Main: typeof import('./src/components/workflow/block-selector/main.vue')['default']
    Node: typeof import('./src/components/workflow/nodes/_base/node/index.vue')['default']
    NodeIcon: typeof import('./src/components/workflow/nodes/_base/nodeIcon/index.vue')['default']
    Nodes: typeof import('./src/components/workflow/nodes/index.vue')['default']
    PanelMain: typeof import('./src/components/strategy-detail/panel-main/index.vue')['default']
    PortalToFollowElem: typeof import('./src/components/base/portal-to-follow-elem/PortalToFollowElem.vue')['default']
    PortalToFollowElemContent: typeof import('./src/components/base/portal-to-follow-elem/PortalToFollowElemContent.vue')['default']
    PortalToFollowElemTrigger: typeof import('./src/components/base/portal-to-follow-elem/PortalToFollowElemTrigger.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/Layout/SideMenu/index.vue')['default']
    SourceHandle: typeof import('./src/components/workflow/nodes/_base/sourceHandle/index.vue')['default']
    Start: typeof import('./src/components/workflow/nodes/start/index.vue')['default']
    Tabs: typeof import('./src/components/workflow/block-selector/tabs.vue')['default']
    TargetHandle: typeof import('./src/components/workflow/nodes/_base/targetHandle/index.vue')['default']
    Tooltip: typeof import('./src/components/base/tooltip/index.vue')['default']
    VariableIcon: typeof import('./src/components/workflow/nodes/_base/variable/variable-label/base/variable-icon.vue')['default']
    VariableIconWithColor: typeof import('./src/components/workflow/nodes/_base/variable/variable-label/variable-icon-with-color.vue')['default']
    VariableLabel: typeof import('./src/components/workflow/nodes/_base/variable/variable-label/base/variable-label.vue')['default']
    VariableLabelInEditor: typeof import('./src/components/workflow/nodes/_base/variable/variable-label/variable-label-in-editor.vue')['default']
    VariableLabelInNode: typeof import('./src/components/workflow/nodes/_base/variable/variable-label/variable-label-in-node.vue')['default']
    VariableLabelInSelect: typeof import('./src/components/workflow/nodes/_base/variable/variable-label/variable-label-in-select.vue')['default']
    VariableLabelInText: typeof import('./src/components/workflow/nodes/_base/variable/variable-label/variable-label-in-text.vue')['default']
    VariableName: typeof import('./src/components/workflow/nodes/_base/variable/variable-label/base/variable-name.vue')['default']
    VariableNodeLabel: typeof import('./src/components/workflow/nodes/_base/variable/variable-label/base/variable-node-label.vue')['default']
    Workflow: typeof import('./src/components/workflow/index.vue')['default']
    WorkflowMain: typeof import('./src/components/strategy-detail/workflow-main/index.vue')['default']
  }
}
