<template>
  <div class="p-8 max-w-7xl mx-auto space-y-6 animate-fade-in h-full">
    <StrategyDetailHeader :data="strategyDetail" />

    <StrategyStatisticPanel :data="strategyDetail" />

    <div
      class="flex items-center gap-3 border-0 border-solid border-b border-gray-800 pb-2"
    >
      <button
        id="tab-overview-btn"
        class="px-4 py-2 rounded-lg text-sm font-bold hover:text-white text-gray-400 bg-transparent hover:bg-gray-800"
        :class="{
          '!bg-teal text-gray-950 hover:text-white': panel === 'overview',
        }"
        @click="panel = 'overview'"
      >
        {{ t(`${i18nPrefix}.tabs.overview`) }}
      </button>
      <button
        id="tab-signals-btn"
        class="px-4 py-2 rounded-lg text-sm text-gray-400 hover:text-white hover:bg-gray-800 bg-transparent"
        :class="{ '!bg-teal text-gray-950': panel === 'signals' }"
        @click="panel = 'signals'"
      >
        {{ t(`${i18nPrefix}.tabs.signals`) }}
      </button>
      <button
        id="tab-performance-btn"
        class="px-4 py-2 rounded-lg text-sm text-gray-400 hover:text-white hover:bg-gray-800 bg-transparent"
        :class="{ '!bg-teal text-gray-950': panel === 'performance' }"
        @click="panel = 'performance'"
      >
        {{ t(`${i18nPrefix}.tabs.performance`) }}
      </button>
    </div>

    <StrategyOverview v-if="panel === 'overview'" :data="strategyDetail" />

    <StrategySignals v-if="panel === 'signals'" :data="signalsList" />

    <StrategyPerformance v-if="panel === 'performance'" :data="strategyDetail"></StrategyPerformance>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import StrategyDetailHeader from "@/components/strategies/detail-header/index.vue";
import StrategyStatisticPanel from "@/components/strategies/statistic-panel/index.vue";
import StrategyOverview from "@/components/strategies/overview/index.vue";
import StrategySignals from "@/components/strategies/signals/index.vue";
import StrategyPerformance from '@/components/strategies/performance/index.vue'

import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const i18nPrefix = 'strategy.detail'

const route = useRoute();
const id = route.query.id;

const strategyDetail = ref({
  id: "1",
  title: "BTC MACD Supertrend",
  symbol: "BTCUSDT",
  timeframe: "15m",
  author: "semantic_yellow",
  connections: 1,
  desc: "This strategy integrates MACD and Supertrend indicators for trading BTC. Generated by conversation history.",
  stats: {
    profit: "+83.39%",
    drawdown: "-34.68%",
    benchReturn: "+22.80%",
    benchDrawdown: "-24.90%",
    winrate: "32.48%",
    trades: "274",
    profitFactor: "1.23",
    signals: "274",
    avgDrawdown: "-7.4%",
    avgDrawdownDays: "4.9 days",
    assetScore: "1.09x",
    assetScoreWidth: "68%",
    totalReturns: "+83.39%",
    cagr: "19.7%",
    avgAnnual: "17.5%",
    positionsCount: "1",
    sectors: "1",
    concentration: "100%",
    sharpe: "1.2",
  },
  isMine: true,
  chatId: "btc-macd",
  positions: [
    {
      symbol: "BTCUSDT",
      allocation: "100%",
      qty: "1.00 BTC",
      avgPrice: "$48,320",
      pnl: "+12.4%",
    },
  ],
  signals: [
    {
      symbol: "BTCUSDT",
      direction: "short",
      status: "pending",
      entryPrice: "$47,850",
      exitPrice: "-",
      entryTime: "2025-01-05 20:00",
      exitTime: "--",
      pnl: "+0.35%",
      agoMins: 18,
    },
    {
      symbol: "BTCUSDT",
      direction: "long",
      status: "executed",
      entryPrice: "$48,000",
      exitPrice: "$49,200",
      entryTime: "2025-01-05 14:30",
      exitTime: "2025-01-05 18:10",
      pnl: "+2.50%",
      agoMins: 60,
    },
    {
      symbol: "BTCUSDT",
      direction: "long",
      status: "executed",
      entryPrice: "$47,600",
      exitPrice: "$48,450",
      entryTime: "2025-01-05 08:10",
      exitTime: "2025-01-05 11:20",
      pnl: "+1.79%",
      agoMins: 210,
    },
    {
      symbol: "BTCUSDT",
      direction: "short",
      status: "executed",
      entryPrice: "$49,400",
      exitPrice: "$48,600",
      entryTime: "2025-01-04 21:30",
      exitTime: "2025-01-05 01:00",
      pnl: "+1.62%",
      agoMins: 900,
    },
    {
      symbol: "BTCUSDT",
      direction: "long",
      status: "executed",
      entryPrice: "$48,700",
      exitPrice: "$49,050",
      entryTime: "2025-01-04 16:00",
      exitTime: "2025-01-04 18:40",
      pnl: "+0.72%",
      agoMins: 1260,
    },
    {
      symbol: "BTCUSDT",
      direction: "short",
      status: "executed",
      entryPrice: "$49,900",
      exitPrice: "$48,950",
      entryTime: "2025-01-04 10:10",
      exitTime: "2025-01-04 13:45",
      pnl: "+1.90%",
      agoMins: 1620,
    },
    {
      symbol: "BTCUSDT",
      direction: "long",
      status: "executed",
      entryPrice: "$47,200",
      exitPrice: "$48,050",
      entryTime: "2025-01-04 03:40",
      exitTime: "2025-01-04 08:10",
      pnl: "+1.80%",
      agoMins: 1980,
    },
    {
      symbol: "BTCUSDT",
      direction: "short",
      status: "executed",
      entryPrice: "$49,600",
      exitPrice: "$48,700",
      entryTime: "2025-01-03 18:00",
      exitTime: "2025-01-03 22:30",
      pnl: "+1.81%",
      agoMins: 2700,
    },
    {
      symbol: "BTCUSDT",
      direction: "long",
      status: "executed",
      entryPrice: "$46,900",
      exitPrice: "$47,950",
      entryTime: "2025-01-03 11:20",
      exitTime: "2025-01-03 15:45",
      pnl: "+2.24%",
      agoMins: 3060,
    },
    {
      symbol: "BTCUSDT",
      direction: "short",
      status: "executed",
      entryPrice: "$50,200",
      exitPrice: "$49,300",
      entryTime: "2025-01-02 20:50",
      exitTime: "2025-01-03 02:10",
      pnl: "+1.79%",
      agoMins: 3900,
    },
  ],
});

const panel = ref("overview");

const signalsList = computed(() => {
  const signals = [...(strategyDetail.value?.signals || [])];
  const ts = (t: string) => {
    const parsed = Date.parse((t || "").replace(" ", "T"));
    return Number.isFinite(parsed) ? parsed : 0;
  };
  signals.sort((a, b) => {
    const diff = ts(b.entryTime) - ts(a.entryTime);
    if (diff !== 0) return diff;
    // If times equal, show pending before executed
    if (a.status === "pending" && b.status !== "pending") return -1;
    if (b.status === "pending" && a.status !== "pending") return 1;
    return 0;
  });
  return signals;
});
</script>
