<template>
  <div class="p-8 max-w-7xl mx-auto animate-fade-in">
      <div class="flex justify-between items-end mb-8">
          <div>
              <h2 class="text-3xl font-bold text-white mb-2">{{ t(`${i18nPrefix}.title`) }}</h2>
              <p class="text-gray-400 text-sm">{{ t(`${i18nPrefix}.description`) }}</p>
          </div>
          <button onclick="app.navigate('home')" class="px-4 py-2 bg-teal text-black font-bold rounded-lg text-sm hover:opacity-90 transition flex items-center gap-2 shadow-[0_0_15px_rgba(0,219,195,0.3)]">
              <RiAddLargeLine class="w-4 h-4" /> {{ t(`${i18nPrefix}.newStrategy`) }}
          </button>
      </div>

      <div id="strategy-lib-grid" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    <!-- 空状态 -->
    <div v-if="!strategies.length" class="col-span-full text-center text-gray-600 bg-gray-900/40 border-solid border border-gray-800 rounded-xl py-12">
      {{ t(`${i18nPrefix}.empty`) }}
    </div>

    <!-- 策略卡片列表 -->
    <StrategyCard
      v-for="strategy in strategies"
      :key="strategy.id"
      :data="strategy"
      :show-share-btn="true"
      :show-connect-btn="true"
      :show-delete-btn="true"
      @delete="removeFromLibrary"
    />
  </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { RiAddLargeLine } from '@remixicon/vue'
import { useI18n } from 'vue-i18n'
import StrategyCard from '@/components/strategies/card/index.vue'

const { t } = useI18n()

const i18nPrefix = 'strategy'

const strategies = ref([
  {
    id: '1',
    title: 'BTC MACD Supertrend',
    symbol: 'BTCUSDT',
    timeframe: '15m',
    author: 'semantic_yellow',
    connections: 1,
    desc: 'This strategy integrates MACD and Supertrend indicators for trading BTC. Generated by conversation history.',
    stats: { 
        profit: '+83.39%', 
        drawdown: '-34.68%', 
        benchReturn: '+22.80%', 
        benchDrawdown: '-24.90%', 
        winrate: '32.48%', 
        trades: '274', 
        profitFactor: '1.23', 
        signals: '274',
        avgDrawdown: '-7.4%',
        avgDrawdownDays: '4.9 days',
        assetScore: '1.09x',
        assetScoreWidth: '68%',
        totalReturns: '+83.39%',
        cagr: '19.7%',
        avgAnnual: '17.5%',
        positionsCount: '1',
        sectors: '1',
        concentration: '100%',
        sharpe: '1.2'
    },
    isMine: true,
    chatId: 'btc-macd',
    positions: [
        { symbol: 'BTCUSDT', allocation: '100%', qty: '1.00 BTC', avgPrice: '$48,320', pnl: '+12.4%' }
    ],
    signals: [
        { symbol: 'BTCUSDT', direction: 'short', status: 'pending', entryPrice: '$47,850', exitPrice: '-', entryTime: '2025-01-05 20:00', exitTime: '--', pnl: '+0.35%', agoMins: 18 },
        { symbol: 'BTCUSDT', direction: 'long', status: 'executed', entryPrice: '$48,000', exitPrice: '$49,200', entryTime: '2025-01-05 14:30', exitTime: '2025-01-05 18:10', pnl: '+2.50%', agoMins: 60 },
        { symbol: 'BTCUSDT', direction: 'long', status: 'executed', entryPrice: '$47,600', exitPrice: '$48,450', entryTime: '2025-01-05 08:10', exitTime: '2025-01-05 11:20', pnl: '+1.79%', agoMins: 210 },
        { symbol: 'BTCUSDT', direction: 'short', status: 'executed', entryPrice: '$49,400', exitPrice: '$48,600', entryTime: '2025-01-04 21:30', exitTime: '2025-01-05 01:00', pnl: '+1.62%', agoMins: 900 },
        { symbol: 'BTCUSDT', direction: 'long', status: 'executed', entryPrice: '$48,700', exitPrice: '$49,050', entryTime: '2025-01-04 16:00', exitTime: '2025-01-04 18:40', pnl: '+0.72%', agoMins: 1260 },
        { symbol: 'BTCUSDT', direction: 'short', status: 'executed', entryPrice: '$49,900', exitPrice: '$48,950', entryTime: '2025-01-04 10:10', exitTime: '2025-01-04 13:45', pnl: '+1.90%', agoMins: 1620 },
        { symbol: 'BTCUSDT', direction: 'long', status: 'executed', entryPrice: '$47,200', exitPrice: '$48,050', entryTime: '2025-01-04 03:40', exitTime: '2025-01-04 08:10', pnl: '+1.80%', agoMins: 1980 },
        { symbol: 'BTCUSDT', direction: 'short', status: 'executed', entryPrice: '$49,600', exitPrice: '$48,700', entryTime: '2025-01-03 18:00', exitTime: '2025-01-03 22:30', pnl: '+1.81%', agoMins: 2700 },
        { symbol: 'BTCUSDT', direction: 'long', status: 'executed', entryPrice: '$46,900', exitPrice: '$47,950', entryTime: '2025-01-03 11:20', exitTime: '2025-01-03 15:45', pnl: '+2.24%', agoMins: 3060 },
        { symbol: 'BTCUSDT', direction: 'short', status: 'executed', entryPrice: '$50,200', exitPrice: '$49,300', entryTime: '2025-01-02 20:50', exitTime: '2025-01-03 02:10', pnl: '+1.79%', agoMins: 3900 }
    ]
  },
  {
    id: '2',
    title: 'Bitcoin Momentum',
    symbol: 'BTCUSDT',
    timeframe: '15m',
    author: 'semantic_yellow',
    connections: 2,
    desc: 'A high-frequency momentum strategy verified by the community. Ideal for bull markets. Created by semantic_yellow.',
    stats: { 
        profit: '+83.39%', 
        drawdown: '-34.68%', 
        benchReturn: '+22.80%', 
        benchDrawdown: '-24.90%', 
        winrate: '32.48%', 
        trades: '274', 
        profitFactor: '1.20', 
        signals: '274',
        avgDrawdown: '-7.4%',
        avgDrawdownDays: '4.9 days',
        assetScore: '1.05x',
        assetScoreWidth: '64%',
        totalReturns: '+83.39%',
        cagr: '18.4%',
        avgAnnual: '16.2%',
        positionsCount: '2',
        sectors: '2',
        concentration: '70%',
        sharpe: '1.2'
    },
    isMine: false,
    positions: [
        { symbol: 'BTCUSDT', allocation: '70%', qty: '1.05 BTC', avgPrice: '$48,100', pnl: '+10.2%' },
        { symbol: 'SOLUSDT', allocation: '12%', qty: '210 SOL', avgPrice: '$96.2', pnl: '+6.5%' }
    ],
    signals: [
        { symbol: 'BTCUSDT', direction: 'long', status: 'executed', entryPrice: '$48,100', exitPrice: '$49,050', entryTime: '2025-01-05 12:10', exitTime: '2025-01-05 16:00', pnl: '+1.97%', agoMins: 120 },
        { symbol: 'BTCUSDT', direction: 'short', status: 'executed', entryPrice: '$49,400', exitPrice: '$48,600', entryTime: '2025-01-04 09:00', exitTime: '2025-01-04 12:30', pnl: '+1.62%', agoMins: 1500 },
        { symbol: 'BTCUSDT', direction: 'long', status: 'pending', entryPrice: '$48,250', exitPrice: '-', entryTime: '2025-01-05 21:10', exitTime: '--', pnl: '+0.10%', agoMins: 5 }
    ]
  },
  {
    id: '3',
    title: 'ETH RSI Breakout',
    symbol: 'ETHUSDT',
    timeframe: '1h',
    author: 'semantic_yellow',
    connections: 1,
    desc: 'RSI breakout with volume confirmation and trailing stop for ETH.',
    stats: { 
        profit: '+45.12%', 
        drawdown: '-18.32%', 
        benchReturn: '+22.80%', 
        benchDrawdown: '-24.90%', 
        winrate: '48.6%', 
        trades: '138', 
        profitFactor: '1.35', 
        signals: '138',
        avgDrawdown: '-5.2%',
        avgDrawdownDays: '3.1 days',
        assetScore: '1.02x',
        assetScoreWidth: '58%',
        totalReturns: '+45.12%',
        cagr: '14.1%',
        avgAnnual: '12.2%',
        positionsCount: '2',
        sectors: '2',
        concentration: '55%',
        sharpe: '1.2'
    },
    isMine: true,
    chatId: 'eth-rsi',
    positions: [
        { symbol: 'ETHUSDT', allocation: '55%', qty: '4.2 ETH', avgPrice: '$2,380', pnl: '+5.4%' },
        { symbol: 'BTCUSDT', allocation: '15%', qty: '0.22 BTC', avgPrice: '$48,050', pnl: '+2.3%' }
    ],
    signals: [
        { symbol: 'ETHUSDT', direction: 'long', status: 'executed', entryPrice: '$2,420', exitPrice: '$2,515', entryTime: '2025-01-05 08:00', exitTime: '2025-01-05 13:00', pnl: '+3.9%', agoMins: 200 },
        { symbol: 'ETHUSDT', direction: 'short', status: 'pending', entryPrice: '$2,500', exitPrice: '-', entryTime: '2025-01-05 21:00', exitTime: '--', pnl: '+0.00%', agoMins: 15 }
    ]
  }
]);

const removeFromLibrary = (id: string) => {
  // 删除后更新列表
  strategies.value = strategies.value.filter(item => item.id !== id);
};

</script>

<style scoped>
/* 卡片基础样式增强 */
.strategy-card {
  @apply transition-all duration-200;
}
</style>